backend:
  name: git-gateway
  branch: main

# TĄ LINIJKĄ WYŁĄCZAMY PODZIELONY EKRAN I WYMUSZAMY WĄSKI WIDOK (JEDNO POD DRUGIM)
editor:
  preview: false

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "galeria_coll"
    label: "Zarządzanie Galerią"
    delete: true
    files:
      - file: "assets/data/galeria.json"
        label: "Lista Projektów"
        name: "galeria_file"
        fields:
          - label: "Projekty w galerii"
            name: "projekty"
            widget: "list"
            summary: '{{fields.tytul}}'
            fields:
              - { label: "Tytuł projektu", name: "tytul", widget: "string" }
              - { label: "Zdjęcie mebla", name: "foto", widget: "image" }
              - { label: "Krótki opis prac", name: "opis", widget: "text", required: false }
